version: 2
jobs:
  build:
    docker:
      - image: buildpack-deps:trusty

    working_directory: ~/repo

    steps:
      - run: echo 'export PATH=/opt/qt55/bin/:$PATH' >> $BASH_ENV

      - checkout

      # Install and configure env with Qt
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y software-properties-common
          sudo add-apt-repository -y ppa:beineri/opt-qt551-trusty
          sudo add-apt-repository -y ppa:george-edison55/cmake-3.x
          sudo apt-get -qy update
          sudo apt-get install -y dbus xvfb curl cmake qt55base qt55webkit qt55graphicaleffects qt55quick1 qt55quickcontrols qt55websockets qt55declarative mesa-common-dev libgl1-mesa-dev
          echo "/opt/qt55/bin/qt55-env.sh" >> ~/.circlerc

      # Install node
      - run: |
          curl -sL https://deb.nodesource.com/setup_8.x | sudo -E bash -
          sudo apt-get install -y nodejs
          
      - run: |
          cmake -version
          qmake -version

      # Repair dbus
      - run: ln -s /var/lib/dbus/machine-id /etc/machine-id

      # Build react-native-linux
      - run: |
          mkdir build
          pushd build
          cmake .. && make -j4
          popd

      # Download and cache dependencies
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}

      - run: npm install

      # Apply metro-bundler patch to add ubuntu platform
      - run: patch --verbose -d ./node_modules/metro-bundler/src -i ../../../add-ubuntu-platform.patch

      - type: shell
        name: Start packager
        command: npm start
        background: true

      - type: shell
        name: Start ubuntu-server.js
        command: node ./ubuntu-server.js
        background: true

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules
        
      # run tests!
      - run: npm test

      # run unit tests
      - run: |
          pushd build
          xvfb-run --server-args="-screen 0 1024x768x24" ctest -VV
          popd